<BaseListItemWithSwitch>
    divider: None
    _no_ripple_effect: True
    on_size: self.ids._right_container.height = dp(64)

    RightSwitchContainer:
        active: root.active
        icon_active: "check"
#        icon_inactive: "close"
#        icon_inactive_color: "white"
        thumb_color_active: "white"
        thumb_color_inactive: "#60675B"
        track_color_active: "darkgreen"
        track_color_inactive: "#D7DECD"

